-- Supabase Database Schema Setup SQL
-- Copy and run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/aztxfncqanrodbttywrb/sql)

-- 1. Create Deals Table (Fallback / Cache table)
CREATE TABLE IF NOT EXISTS public.deals (
    id TEXT PRIMARY KEY,
    deal_id_zoho TEXT NOT NULL,
    custom_id TEXT NOT NULL,
    deal_name TEXT,
    arrival_date TEXT,
    region TEXT,
    language TEXT,
    stage TEXT,
    owner_name TEXT,
    team_name TEXT,
    status TEXT DEFAULT 'pending',
    result_code TEXT,
    agent_note TEXT,
    lock_approval_requested BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;

-- Create policy for public insert/update/select/delete
CREATE POLICY "Public Access Policy" ON public.deals 
    FOR ALL USING (true) WITH CHECK (true);


-- 2. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id TEXT PRIMARY KEY,
    "user" TEXT,
    action TEXT,
    deal_id TEXT,
    deal_name TEXT,
    details TEXT,
    timestamp TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on audit_logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for public access
CREATE POLICY "Public Access Policy" ON public.audit_logs 
    FOR ALL USING (true) WITH CHECK (true);


-- 3. Create Users Directory Table (Matches exact casing of your Excel upload)
CREATE TABLE IF NOT EXISTS public."Users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Deal Owner Name" TEXT,
    "Username" TEXT,
    "Password" TEXT,
    "Role" TEXT,
    "Takim Adi" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on Users
ALTER TABLE public."Users" ENABLE ROW LEVEL SECURITY;

-- Create policy for public access
CREATE POLICY "Public Access Policy" ON public."Users" 
    FOR ALL USING (true) WITH CHECK (true);
