// Admin panelindeki "Users" sayfasının (listeleme/ekleme/düzenleme/silme)
// tüm Users tablosu erişimi buradan geçer — service_role key ile, sunucu
// tarafında. Bu sayede Users tablosunun RLS'i anon key'e tamamen
// kapatılabilir (bkz. admin_summary_rpc.sql yanındaki lockdown SQL'i) —
// tarayıcı artık bu tabloya hiçbir zaman doğrudan dokunmuyor.
//
// Auth: çağıranın api/login.js'te üretilen imzalı, süresi dolmamış ve
// admin/super-admin rolüne ait bir token'ı Authorization: Bearer başlığında
// göndermesi ZORUNLU — aksi halde 401. Bu olmadan bu uç, service_role
// yetkisiyle Users tablosunda TAM CRUD (parola değiştirme/kullanıcı
// silme dahil) yapabilen, kimliği doğrulanmamış herkese açık bir endpoint
// olurdu.
import bcrypt from 'bcryptjs';
import { verifyToken, bearerToken } from './_auth.js';
import { isBlocked, BLOCKED_NAMES } from './_blocked-users.js';

const FALLBACK_URL = 'https://aztxfncqanrodbttywrb.supabase.co';

// ════════════════════════════════════════════════════════════════════════
// Kullanıcı ekleme: "hata verdi" diyen iki gerçek sebebi kendi kendine
// toparlar. Panelden eklemek çalışmıyordu ve ekranda yalnızca ham
// PostgREST metni görünüyordu.
//
//  1) TEKRARLAYAN BİRİNCİL ANAHTAR (23505)
//     Users.id "GENERATED BY DEFAULT AS IDENTITY". Tablo Excel'den
//     yüklenirken satırlar AÇIK id ile geldi (Zoho'nun 18 haneli id'leri),
//     yani identity dizisi hiç ilerlemedi — dizi hâlâ 1, 2, 3... veriyor.
//     Daha önce eklenmiş bir satır o değerleri kapmışsa yeni ekleme
//     "duplicate key" ile patlıyor ve her denemede aynı hatayı veriyor.
//     Çözüm: çakışmada mevcut en büyük id'yi bulup +1 ile açıkça yaz.
//     id BIGINT olduğu için değeri METİN olarak gönderiyoruz — JS sayısı
//     18 hanede yuvarlanır ve yanlış id yazardı.
//
//  2) OLMAYAN KOLON (42703 / PGRST204)
//     Panel Phone / Email / is_active da yazıyor. Bu kolonlar ayrı .sql
//     dosyalarıyla ekleniyor; biri çalıştırılmamışsa TÜM ekleme başarısız
//     oluyordu — oysa bunlar isteğe bağlı alanlar. Çözüm: eksik kolonu
//     yükten düşür ve tekrar dene, zorunlu alanlar kaydedilsin.
// ════════════════════════════════════════════════════════════════════════

// PostgREST hata gövdesinden kod ve mesajı çıkarır (gövde JSON olmayabilir).
function pgErr(text) {
  try {
    const j = JSON.parse(text);
    return { code: j.code || '', message: j.message || '', details: j.details || '' };
  } catch (e) {
    return { code: '', message: String(text || ''), details: '' };
  }
}

// Hata mesajından eksik kolonun adını çıkarır: 'column "Phone" of relation ...'
function missingColumn(err, payload) {
  const m = /column "?([^"']+)"? (?:of relation|does not exist)/i.exec(err.message + ' ' + err.details);
  if (m && Object.prototype.hasOwnProperty.call(payload, m[1])) return m[1];
  // PGRST204: "Could not find the 'Phone' column of 'Users' in the schema cache"
  const m2 = /could not find the '([^']+)' column/i.exec(err.message);
  if (m2 && Object.prototype.hasOwnProperty.call(payload, m2[1])) return m2[1];
  return null;
}

async function maxUserId(SUPABASE_URL, H) {
  // id::text ile çekiyoruz: 18 haneli bigint JSON sayısı olarak yuvarlanır.
  const r = await fetch(`${SUPABASE_URL}/rest/v1/Users?select=id_text:id::text&order=id.desc&limit=1`,
    { headers: H });
  if (!r.ok) return null;
  const rows = await r.json();
  const t = Array.isArray(rows) && rows[0] && rows[0].id_text;
  return t ? String(t) : null;
}

// Metin olarak tutulan tamsayıya 1 ekler (BigInt: 18 hane güvenli değil).
function plusOne(idText) {
  try { return (BigInt(idText) + 1n).toString(); } catch (e) { return null; }
}

async function insertUser(SUPABASE_URL, H, HJ, payloadIn) {
  const payload = { ...payloadIn };
  const dropped = [];
  // En fazla 5 deneme: her deneme ya bir kolon düşürür ya id atar; sonsuz
  // döngü olamaz çünkü ikisi de sonlu.
  for (let attempt = 0; attempt < 5; attempt++) {
    const r = await fetch(`${SUPABASE_URL}/rest/v1/Users`, {
      method: 'POST',
      headers: { ...HJ, Prefer: 'return=representation' },
      body: JSON.stringify(payload)
    });
    if (r.ok) return { rows: await r.json(), dropped };

    const err = pgErr(await r.text());

    const col = missingColumn(err, payload);
    if (col) { delete payload[col]; dropped.push(col); continue; }

    // Birincil anahtar çakışması → en büyük id + 1 ile açıkça yaz.
    const isDup = err.code === '23505';
    const onPk  = /Users_pkey|\bid\b/i.test(err.message + ' ' + err.details);
    if (isDup && onPk && !payload.id) {
      const mx = await maxUserId(SUPABASE_URL, H);
      const next = mx && plusOne(mx);
      if (next) { payload.id = next; continue; }
    }
    if (isDup && !onPk) {
      return { status: 409, error: 'Bu kayıt zaten var: ' + (err.message || 'tekrarlayan değer') };
    }

    return { status: 502, error: err.message || 'Veritabanı hatası.' };
  }
  return { status: 502, error: 'Kullanıcı eklenemedi: birden fazla deneme başarısız oldu.' };
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');

  const SUPABASE_URL = process.env.SUPABASE_URL || FALLBACK_URL;
  const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!SERVICE_KEY) {
    res.status(500).json({ error: 'Sunucu yapılandırma hatası: SUPABASE_SERVICE_ROLE_KEY eksik.' });
    return;
  }
  const AUTH_SECRET = process.env.AUTH_TOKEN_SECRET;
  if (!AUTH_SECRET) {
    res.status(500).json({ error: 'Sunucu yapılandırma hatası: AUTH_TOKEN_SECRET eksik.' });
    return;
  }
  const claims = verifyToken(bearerToken(req), AUTH_SECRET);
  if (!claims || (claims.r !== 'admin' && claims.r !== 'super-admin')) {
    res.status(401).json({ error: 'Yetkisiz erişim.' });
    return;
  }

  const H  = { apikey: SERVICE_KEY, Authorization: 'Bearer ' + SERVICE_KEY };
  const HJ = { ...H, 'Content-Type': 'application/json; charset=utf-8' };

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch (e) { body = {}; } }

  try {
    if (req.method === 'GET') {
      // id_text: id'nin KESIN degeri, metin olarak. Users.id 18 haneli bir
      // bigint ve JS'in guvenli tamsayi sinirini (2^53) asiyor — JSON'da sayi
      // olarak tasindiginda yuvarlaniyor ve FARKLI iki kisinin id'si ayni
      // degere donusebiliyor. Panel bu yuzden satirlari id ile hedeflemiyor;
      // id_text yalnizca ekranda dogru deger gorunsun diye var.
      const r = await fetch(
        `${SUPABASE_URL}/rest/v1/Users?select=*,id_text:id::text&order=id.asc&limit=1000`,
        { headers: H });
      if (!r.ok) { res.status(502).json({ error: 'Veritabanı hatası: ' + (await r.text()) }); return; }
      let users = await r.json();
      // Sistemden CIKARILMIS kisiler listede gorunmez (bkz. _blocked-users.js).
      // Satirlari silmiyoruz: gecmis veri (daily_performance, alarm_logs) onlara
      // bagli. Gorunmez + giris yapamaz olmalari yeterli.
      users = users.filter(u => !isBlocked(u['Deal Owner Name'], u['Username']));
      // Şifre: bcrypt HASH'i asla dönmez — geri çevrilemez, panelde de bir işe
      // yaramaz, sızması zarar verir. Bunun yerine iki türev alan dönüyor:
      //   passwordSet   → şifre tanımlı mı (boş hesapları görebilmek için)
      //   passwordPlain → SADECE kayıt henüz hashlenmemişse (eski kayıtlar;
      //                   api/login.js ilk başarılı girişte hashliyor). Bu
      //                   değer veritabanında zaten düz metin duruyor ve bu uç
      //                   admin/super-admin token'ı zorunlu kılıyor; admine
      //                   göstermek yeni bir sızma yüzeyi açmıyor, mevcut
      //                   şifresini soran kullanıcıya cevap verebilmesini
      //                   sağlıyor. Hashlenmiş kayıtlarda hiç dönmez.
      users.forEach(u => {
        const stored = String(u.Password == null ? '' : u.Password);
        const hashed = /^\$2[aby]\$/.test(stored);
        u.passwordSet   = stored.trim() !== '';
        u.passwordPlain = (!hashed && stored.trim() !== '') ? stored : null;
        delete u.Password;
      });
      res.status(200).json({ users });
      return;
    }

    if (req.method === 'POST') {
      const payload = { ...(body?.payload || {}) };
      // Engelli bir adla yeniden olusturmayi reddet -- yoksa 'sildim, geri geldi'
      // dongusu surer.
      if (isBlocked(payload['Deal Owner Name'], payload['Username'])) {
        res.status(403).json({ error: 'Bu kisi sistemden cikarildi, yeniden eklenemez.' });
        return;
      }
      const newUsername = String(payload['Username'] || '').trim();
      if (!newUsername) { res.status(400).json({ error: 'Kullanıcı adı zorunlu.' }); return; }
      // Ayni kullanici adi zaten varsa: veritabani hatasi beklemek yerine net
      // soyle. Kullanici adi giris anahtari, cift olmasi girisi belirsiz yapar.
      const dupR = await fetch(
        `${SUPABASE_URL}/rest/v1/Users?Username=eq.${encodeURIComponent(newUsername)}&select=Username`,
        { headers: H });
      if (dupR.ok) {
        const dup = await dupR.json();
        if (Array.isArray(dup) && dup.length) {
          res.status(409).json({ error: `"${newUsername}" kullanıcı adı zaten kayıtlı. Farklı bir kullanıcı adı seçin.` });
          return;
        }
      }
      if (payload.Password) payload.Password = await bcrypt.hash(payload.Password, 10);
      const created = await insertUser(SUPABASE_URL, H, HJ, payload);
      if (created.error) { res.status(created.status || 502).json({ error: created.error }); return; }
      const rows = created.rows;
      if (Array.isArray(rows)) rows.forEach(u => { delete u.Password; });
      res.status(200).json({ ok: true, user: rows?.[0] || null });
      return;
    }

    if (req.method === 'PATCH') {
      const { id, username, payload: rawPayload } = body || {};
      if (!id && !username) { res.status(400).json({ error: 'id veya username gerekli.' }); return; }
      const payload = { ...(rawPayload || {}) };
      // Şifre alanı boş bırakılmışsa (kullanıcı değiştirmek istemiyor) hiç
      // gönderilmesin — boş string'i hashleyip üzerine yazmayalım.
      if (isBlocked(payload['Deal Owner Name'], payload['Username'])) {
        res.status(403).json({ error: 'Bu kisi sistemden cikarildi, bu ada guncellenemez.' });
        return;
      }
      if (!payload.Password) delete payload.Password;
      else payload.Password = await bcrypt.hash(payload.Password, 10);
      const filterKey = username ? `Username=eq.${encodeURIComponent(username)}` : `id=eq.${encodeURIComponent(id)}`;
      // POST ile ayni mantik: olmayan istege bagli kolon (Phone/Email/
      // is_active) TUM guncellemeyi bosa dusurmesin, o alani dusurup devam et.
      const patchPayload = { ...payload };
      let pr = null;
      for (let attempt = 0; attempt < 4; attempt++) {
        pr = await fetch(`${SUPABASE_URL}/rest/v1/Users?${filterKey}`, {
          method: 'PATCH',
          headers: { ...HJ, Prefer: 'return=minimal' },
          body: JSON.stringify(patchPayload)
        });
        if (pr.ok) break;
        const err = pgErr(await pr.text());
        const col = missingColumn(err, patchPayload);
        if (col) { delete patchPayload[col]; continue; }
        res.status(err.code === '23505' ? 409 : 502).json({ error: err.message || 'Veritabanı hatası.' });
        return;
      }
      if (!pr || !pr.ok) { res.status(502).json({ error: 'Güncelleme başarısız.' }); return; }
      res.status(200).json({ ok: true });
      return;
    }

    if (req.method === 'DELETE') {
      const { id, username } = body || {};
      if (!id && !username) { res.status(400).json({ error: 'id veya username gerekli.' }); return; }
      const filterKey = username ? `Username=eq.${encodeURIComponent(username)}` : `id=eq.${encodeURIComponent(id)}`;
      const r = await fetch(`${SUPABASE_URL}/rest/v1/Users?${filterKey}`, {
        method: 'DELETE',
        headers: { ...H, Prefer: 'return=minimal' }
      });
      if (!r.ok) { res.status(502).json({ error: pgErr(await r.text()).message || 'Veritabanı hatası.' }); return; }
      res.status(200).json({ ok: true });
      return;
    }

    res.status(405).json({ error: 'Method not allowed' });
  } catch (e) {
    res.status(500).json({ error: 'Sunucu hatası: ' + e.message });
  }
}
